# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Kuliah\smester4\pbo2\tugas\postgres-ribbon\ui\alumni.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 503)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 71, 16))
        self.label_2.setObjectName("label_2")
        self.txtkode = QtWidgets.QLineEdit(self.centralwidget)
        self.txtkode.setGeometry(QtCore.QRect(160, 80, 141, 20))
        self.txtkode.setObjectName("txtkode")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 110, 91, 16))
        self.label_3.setObjectName("label_3")
        self.txtNama = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNama.setGeometry(QtCore.QRect(160, 110, 291, 20))
        self.txtNama.setObjectName("txtNama")
        self.optLaki = QtWidgets.QRadioButton(self.centralwidget)
        self.optLaki.setGeometry(QtCore.QRect(160, 150, 82, 17))
        self.optLaki.setObjectName("optLaki")
        self.optPerempuan = QtWidgets.QRadioButton(self.centralwidget)
        self.optPerempuan.setGeometry(QtCore.QRect(160, 180, 82, 17))
        self.optPerempuan.setObjectName("optPerempuan")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 150, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 210, 81, 16))
        self.label_5.setObjectName("label_5")
        self.btnSimpan = QtWidgets.QPushButton(self.centralwidget)
        self.btnSimpan.setGeometry(QtCore.QRect(160, 250, 75, 23))
        self.btnSimpan.setStyleSheet("#btnSimpan{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 255);\n"
"}")
        self.btnSimpan.setObjectName("btnSimpan")
        self.gridAlumni = QtWidgets.QTableWidget(self.centralwidget)
        self.gridAlumni.setGeometry(QtCore.QRect(20, 290, 541, 192))
        self.gridAlumni.setRowCount(10)
        self.gridAlumni.setColumnCount(5)
        self.gridAlumni.setObjectName("gridAlumni")
        self.btnCari = QtWidgets.QPushButton(self.centralwidget)
        self.btnCari.setGeometry(QtCore.QRect(310, 80, 41, 23))
        self.btnCari.setObjectName("btnCari")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(240, 250, 75, 23))
        self.btnClear.setStyleSheet("#btnClear{\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.btnClear.setObjectName("btnClear")
        self.btnHapus = QtWidgets.QPushButton(self.centralwidget)
        self.btnHapus.setGeometry(QtCore.QRect(320, 250, 75, 23))
        self.btnHapus.setStyleSheet("#btnHapus{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"")
        self.btnHapus.setObjectName("btnHapus")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 140, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.txtTahun = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTahun.setGeometry(QtCore.QRect(160, 210, 81, 20))
        self.txtTahun.setObjectName("txtTahun")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Data Alumni"))
        self.label_2.setText(_translate("MainWindow", "Kode Alumni"))
        self.label_3.setText(_translate("MainWindow", "Nama Lengkap"))
        self.optLaki.setText(_translate("MainWindow", "Laki-laki"))
        self.optPerempuan.setText(_translate("MainWindow", "Perempuan"))
        self.label_4.setText(_translate("MainWindow", "Jenis Kelamin"))
        self.label_5.setText(_translate("MainWindow", "Tahun Lulus"))
        self.btnSimpan.setText(_translate("MainWindow", "Simpan"))
        self.btnCari.setText(_translate("MainWindow", "cari"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.btnHapus.setText(_translate("MainWindow", "Hapus"))
        self.label_6.setText(_translate("MainWindow", "Kevin Alfito - 200511101"))
