# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Kuliah\smester4\pbo2\tugas\postgres-ribbon\ui\matakuliah.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 499)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtKodeMK = QtWidgets.QLineEdit(self.centralwidget)
        self.txtKodeMK.setGeometry(QtCore.QRect(140, 80, 141, 20))
        self.txtKodeMK.setObjectName("txtKodeMK")
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(220, 210, 75, 23))
        self.btnClear.setStyleSheet("#btnClear{\n"
"    background-color: rgb(0, 255, 0);\n"
"}")
        self.btnClear.setObjectName("btnClear")
        self.btnSimpan = QtWidgets.QPushButton(self.centralwidget)
        self.btnSimpan.setGeometry(QtCore.QRect(140, 210, 75, 23))
        self.btnSimpan.setStyleSheet("#btnSimpan{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 255);\n"
"}")
        self.btnSimpan.setObjectName("btnSimpan")
        self.btnCari = QtWidgets.QPushButton(self.centralwidget)
        self.btnCari.setGeometry(QtCore.QRect(290, 80, 41, 23))
        self.btnCari.setObjectName("btnCari")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.txtNamaMK = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNamaMK.setGeometry(QtCore.QRect(140, 110, 291, 20))
        self.txtNamaMK.setObjectName("txtNamaMK")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 91, 16))
        self.label_3.setObjectName("label_3")
        self.btnHapus = QtWidgets.QPushButton(self.centralwidget)
        self.btnHapus.setGeometry(QtCore.QRect(300, 210, 75, 23))
        self.btnHapus.setStyleSheet("#btnHapus{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"")
        self.btnHapus.setObjectName("btnHapus")
        self.txtSKS = QtWidgets.QLineEdit(self.centralwidget)
        self.txtSKS.setGeometry(QtCore.QRect(140, 140, 51, 20))
        self.txtSKS.setObjectName("txtSKS")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 140, 91, 16))
        self.label_4.setObjectName("label_4")
        self.gridMatakuliah = QtWidgets.QTableWidget(self.centralwidget)
        self.gridMatakuliah.setGeometry(QtCore.QRect(10, 260, 541, 192))
        self.gridMatakuliah.setRowCount(10)
        self.gridMatakuliah.setColumnCount(4)
        self.gridMatakuliah.setObjectName("gridMatakuliah")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.btnSimpan.setText(_translate("MainWindow", "Simpan"))
        self.btnCari.setText(_translate("MainWindow", "cari"))
        self.label.setText(_translate("MainWindow", "Data Matakuliah"))
        self.label_2.setText(_translate("MainWindow", "Kode MK"))
        self.label_3.setText(_translate("MainWindow", "Nama Matakuliah"))
        self.btnHapus.setText(_translate("MainWindow", "Hapus"))
        self.label_4.setText(_translate("MainWindow", "SKS"))
        self.label_6.setText(_translate("MainWindow", "Kevin Alfito - 200511101"))
